# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9bC9Qu5oz88X1FohIk3teVslm5Vps_o
"""

orders = []


def login():
    username = input("Enter Username: ")
    password = input("Enter Password: ")

    if username == "nishi" and password == "12345":
        print("\nLogin Successful!")
        return True
    else:
        print("Invalid Username or Password")
        return False


def add_order():
    order_id = input("\nEnter Order ID: ")
    customer = input("Enter Customer Name: ")
    items = []

    while True:
        print("\n========== FOOD MENU ==========")
        print("1. Burger - Rs.1200")
        print("2. Pizza - Rs.2500")
        print("3. Fries - Rs.800")
        print("4. Juice - Rs.500")
        print("5. Finish Order")

        choice = input("Select Item: ")

        if choice == "5":
            if len(items) == 0:
                print("Add at least one item!")
                continue
            break

        try:
            qty = int(input("Enter Quantity: "))
            if qty <= 0:
                print("Quantity must be greater than 0!")
                continue
        except ValueError:
            print("Invalid input! Please enter a number for quantity.")
            continue

        if choice == "1":
            food = "Burger"
            amount = qty * 1200
        elif choice == "2":
            food = "Pizza"
            amount = qty * 2500
        elif choice == "3":
            food = "Fries"
            amount = qty * 800
        elif choice == "4":
            food = "Juice"
            amount = qty * 500
        else:
            print("Invalid Choice!")
            continue

        items.append({
            "food": food,
            "qty": qty,
            "amount": amount
        })

        print(f"{food} Added Successfully!")

    orders.append({
        "id": order_id,
        "customer": customer,
        "items": items,
        "status": "Pending"
    })

    print("\nOrder Saved Successfully!")


def view_orders():
    if len(orders) == 0:
        print("\nNo Orders Found!")
        return

    print("\n========== ALL ORDERS ==========")
    for order in orders:
        print("\nOrder ID:", order["id"])
        print("Customer:", order["customer"])

        total = 0
        for item in order["items"]:
            print(f"Food: {item['food']} | Qty: {item['qty']} | Amount: Rs. {item['amount']}")
            total += item["amount"]

        print("Order Total = Rs.", total)
        print("Status =", order["status"])


def search_order():
    search = input("Enter Order ID to Search: ")
    found = False

    for order in orders:
        if order["id"] == search:
            print("\n========== SEARCH RESULT ==========")
            print("Order ID:", order["id"])
            print("Customer:", order["customer"])
            print("Status:", order["status"])

            total = 0
            for item in order["items"]:
                print(f"{item['food']} - Qty: {item['qty']}")
                total += item["amount"]

            print("Total Amount = Rs.", total)
            found = True
            break

    if not found:
        print("Order Not Found")


def update_status():
    search = input("Enter Order ID: ")
    found = False

    for order in orders:
        if order["id"] == search:
            print("Current Status:", order["status"])
            print("1. Set as Pending")
            print("2. Set as Completed")

            status_choice = input("Select New Status (1 or 2): ")

            if status_choice == "1":
                order["status"] = "Pending"
                print("Status Updated to Pending!")
            elif status_choice == "2":
                order["status"] = "Completed"
                print("Status Updated to Completed!")
            else:
                print("Invalid Choice! Status not changed.")

            found = True
            break

    if not found:
        print("Order Not Found")


def calculate_total_sales():
    sales = 0
    for order in orders:
        if order["status"] == "Completed":
            for item in order["items"]:
                sales += item["amount"]

    print("\nTotal Sales (Completed Orders) = Rs.", sales)


def count_completed_orders():
    count = 0
    for order in orders:
        if order["status"] == "Completed":
            count += 1

    print("\nCompleted Order Count =", count)


def main_menu():
    while True:
        print("\n========== MAIN MENU ==========")
        print("1. Add Order")
        print("2. View Orders")
        print("3. Search Order")
        print("4. Update Order Status")
        print("5. Display Total Sales")
        print("6. Count Completed Orders")
        print("7. Exit")

        choice = input("Enter Choice: ")

        if choice == "1":
            add_order()
        elif choice == "2":
            view_orders()
        elif choice == "3":
            search_order()
        elif choice == "4":
            update_status()
        elif choice == "5":
            calculate_total_sales()
        elif choice == "6":
            count_completed_orders()
        elif choice == "7":
            print("Thank You for using the system!")
            break
        else:
            print("Invalid Choice!")


if login():
    main_menu()