# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SFXhtJMN3BRJ9h-o0Wyh1_ftrTRK1WTQ
"""

friends=["dinithi","tharushi","slaini"]
x,y,z=friends
print(x)
print(y)
print(z)

x="i don't like python"
print(x)

x=30
y=15
z=x+y
d=z/2
print (d)

x="class"
def myfunc():
  print("wellcome to "+x)
myfunc()

x="understand"
def myfunc():
  x="fantastic"
  print("pythone is "+x)
myfunc()
print("but i cant "+x)

def myfunc():
  global x
  x="fantastic"
myfunc()

print("python is "+x)

x=5
print(type(x))

x="wellcome"
print(type(x))

x=1
a=float(x)
print(a)
print(type(a))

print(10>9)
print(10==9)
print(10<9)

a=200
b=33
if b>a:
  print("b is greater than a")
else:
  print("b is not greater than a")

x=5
print(x>0 and x<10)
y=5
print(not(x>3 and x<10))

x=[1,2,3]
y=[1,2,3]
print(x==y)
print(x is y)

thislist=["apple","banana","cherry","apple","cherry"]
print(thislist)

thislist=["apple","banana","cherry"]
print(thislist[0])

thislist=["apple","banan","cherry"]
print(thislist[-1])

thislist=["apple","banana","cherry"]
if "apple" in thislist:
  print("yes,'apple' is in the fruit list")

thislist=["apple","banana","cherry"]
thislist[1]="blackcurrant"
print(thislist)

thislist=["apple","banana","cherry"]
thislist.append("orange")
print(thislist)

thislist=["apple","banana","cherry"]
thislist.insert(1,"orange")
print(thislist)

thislist=["apple","cherry","banana","kiwi"]
thislist.remove("banana")
print(thislist)

thislist=["apple","banana","cherry"]
del thislist[0]
print(thislist)

thistuple=("apple","banana","cherry")
print(thistuple)

thisset={"zoo","bat","mango","mother","art","sahan"}
print(thisset)

thisdict={
    "brand":"ford",
    "model":"mustang",
    "year":1964
}
print(thisdict)

number=-20
if number>0:
  print("the number is positive")
else:
  print("the number is negative")

a=33
b=33
if b>a:
  print("b is greater than a")
elif a==b:
  print("a equal to b")

age=25
has_license=True
if age >=18:
  if has_license:
    print("you can drive")
  else:
    print("you need a license")
else:
  print("you are too young to drive")

marks=54
has_student_id=True
if marks >=50:
  if has_student_id:
    print("you are pass")
  else:
    print("you need a student id")
else:
  print("you were repeated")

marks=int(input("please enter your marks:"))
id=input("do you have a student id:")
if marks>=50:
  if id=="yes":
    print("you are pass")
  else:
    print("you need a student id")
else:
  print("you are faill")

marks=40
if marks >=80:
    print("A pass")
elif marks>=60:
    print("B pass")
elif marks>=50:
    print("C pass")
else:
  print("fail")

marks = float(input("Please enter the marks: "))
if marks >=80:
    print("A pass")
elif marks>=60:
    print("B pass")
elif marks>=50:
    print("C pass")
else:
  print("fail")

i=1
while i<50:
  print(i)
  i+=1

i=1
while i<6:
  print(i)
  if i == 3:
    break
  i+=1

for i in range(1,50):
  print(i)

vehicles =["car","jeep","van"]
for t in vehicles:
  print(t)
  if t=="jeep":
    break

for i in range(1,4):
  for j in range(1,4):
    print(i,j)

for i in range(1,20):
  if i>14:
    print(i)
  else:
    print("hi")

name=str(input("please enter your name: "))
print("hello",name)

m1=int(input("please enter the  maths marks: "))
m2=int(input("please enter the  English marks: "))
m3=int(input("please enter the core maths marks: "))
m4=int(input("please enter the DMC marks: "))
total=int(m1+m2+m3+m4)
average=int(total/4)
print("your total marks is",total)
print("your average marks is",average)

try:
  print(x)
except:
  print("an exception occured")

try:
  a=int(input("enter first number: "))
  b=int(input("enter second number: "))
  result=a/b
  print("result:",result)
except ValueError:
  print("error:please enter only number.")
except ZeroDivisionError:
  print("error:cannot divide by zero.")

try:
  num=int(input("enter number:"))
except ValueError:
  print("not a valid number!")
else:
  print("good job,you entered:",num)
finally:
  print("program finished")

m1=float(input("please enter the  maths marks: "))
m2=float(input("please enter the  English marks: "))
m3=float(input("please enter the core maths marks: "))
total=float(m1+m2+m3)
average=float(total/4)
print("your total marks is",total)
print("your average marks is",average)
if average>=75:
     print("A pass")
elif average>=65:
    print("B pass")
elif average>=45:
    print("C pass")
else:
  print("fail")

shopping_list = []

for i in range(5):
    item = input("Enter item: ")
    shopping_list.append(item)

print("-Shopping List-:")
for item in shopping_list:
    print(item)

thisdict = {
    "Name": input("Enter name: "),
    "Age": input("Enter age: "),
    "Course": input("Enter course: ")
}

print("Student Record:", thisdict)

try:
    num = int(input("Enter a number: "))
    print("You entered:", num)
except:
    print("Invalid input! Please enter a number.")

def input_marks():
    marks = []
    for i in range(3):
        m = int(input("Enter mark: "))
        marks.append(m)
    return marks

def calculate_total(marks):
    return sum(marks)

def calculate_average(total):
    return total / 3

def print_report(total, average):
    print("Total:", total)
    print("Average:", average)

marks = input_marks()
total = calculate_total(marks)
average = calculate_average(total)
print_report(total, average)

def get_grade(avg):
    if avg >= 75:
        return "A"
    elif avg >= 65:
        return "B"
    elif avg >= 50:
        return "C"
    else:
        return "F"

average = float(input("Enter average: "))
print("Grade:", get_grade(average))

def create_list():
    items = []
    for i in range(5):
        item = input("Enter item: ")
        items.append(item)
    return items

shopping_list = create_list()

print("Shopping List:")
for item in shopping_list:
    print(item)

def create_student():
    student = {}
    student["name"] = input("Enter name: ")
    student["age"] = input("Enter age: ")
    student["course"] = input("Enter course: ")
    return student

student = create_student()
print("Student Record:", student)

thislist = ["apple", "banana", "cherry"]
thislist.append ("orrange")
print(thislist)

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

if a > b:
    print(f"{a} is the greatest number")
else:
    print(f"{b} is the greatest number")

m1=input("please enter the  maths marks: ")
m2=input("please enter the  English marks: ")
m3=input("please enter the core maths marks: ")
total=int(m1)+int(m2)+int(m3)
average=(total/3)
print("total:",total)
print("average:",average)

avg=float(input("please enter the average marks: "))
if avg>=75:
    print("Grade: A")
elif avg>=65:
    print("Grade: B")
elif avg>=50:
    print("grade: C")
else:
    print("Grade: fail")

shopping_list = []
for i in range(5):
    item = input(f"Enter item {i+1}: ")
    shopping_list.append(item)

print("Shopping List:")
for item in shopping_list:
    print("- " + item)

shoping_list=[]
for i in range(5):
  item=(input("enter the item name"))
  shoping_list.append(item)
  print("shoping list: ")
  for item in shoping_list:
    print(item)

student={
    "name":input("enter name: "),
    "age":int(input("enter age: ")),
    "course":input("enter course: ")
}
print("student record:",student)

try:
    num = int(input("Enter a number: "))
    print("You entered:", num)
except:
    print("Invalid input! Please enter a number.")

def get_report():
  m1=float(input("maths: "))
  m2=float(input("English: "))
  m3=float(input("core maths: "))
  total=m1+m2+m3
  average=total/3
  print("total",total)
  print("average",average)
get_report()

def calculate_grade(avg):
    if avg >= 75:
        return "A"
    elif avg >= 65:
        return "B"
    elif avg >= 50:
        return "C"
    else:


        return "F"
marks=float(input("enter average"))
print("grade:",calculate_grade(marks))

def create_list():
    items = []
    for i in range(5):
        item = input("Enter item: ")
        items.append(item)
    return items

shopping_list = create_list()

print("Shopping List:")
for item in shopping_list:
    print(item)

def create_student():
    student = {}
    student["name"] = input("Enter name: ")
    student["age"] = input("Enter age: ")
    student["course"] = input("Enter course: ")
    return student

student = create_student()
print("Student Record:", student)

balance = 10000

def check_balance():
  print("your current balance is RS.", balance)

def deposit_money():
  global balance
  amount = float(input("enter amount to deposite:"))

  if amount > 0:
    balance += amount
    print("deposite successful")
  else:
    print("invalide amount")

def withdraw_money():
  global balance
  amount = float(input("enter amount to withdraw:"))

  if amount <=0:
    print("invalide amount")
  elif amount > balance:
    print("Insufficient balance")
  else:
    balance -= amount
    print("withdrawal successful")


while True:
  print("\n     WELCOME")
  print("1. Check Balance")
  print("2. Deposit")
  print("3. Withdraw")
  print("4. Exit")

  choice = input("enter your choice (1-4):")

  if choice == '1':
    check_balance()

  elif choice == '2':
    deposit_money()

  elif choice == '3':
    withdraw_money()

  elif choice == '4':
    print("Thank You Come Again")
    break
  else:
    print("Invalide choice! try again.")

balance1 = 10000
balance2 = 5000

def check_balance():
    print("\nAccount 1 balance: Rs.", balance1)
    print("Account 2 balance: Rs.", balance2)


def deposit_money():
    global balance1, balance2

    acc = input("Deposit to (1 or 2): ")
    amount = float(input("Enter amount: "))

    if amount <= 0:
        print("Invalid amount")

    elif acc == "1":
        balance1 += amount
        print("Deposit successful")

    elif acc == "2":
        balance2 += amount
        print("Deposit successful")

    else:
        print("Invalid account")


def withdraw_money():
    global balance1, balance2

    acc = input("Withdraw from (1 or 2): ")
    amount = float(input("Enter amount: "))

    if amount <= 0:
        print("Invalid amount")

    elif acc == "1":
        if amount <= balance1:
            balance1 -= amount
            print("Withdrawal successful")
        else:
            print("Insufficient balance")

    elif acc == "2":
        if amount <= balance2:
            balance2 -= amount
            print("Withdrawal successful")
        else:
            print("Insufficient balance")

    else:
        print("Invalid account")


def transfer_money():
    global balance1, balance2

    print("1. Account 1 → Account 2")
    print("2. Account 2 → Account 1")

    option = input("Choose option (1 or 2): ")
    amount = float(input("Enter amount: "))

    if amount <= 0:
        print("Invalid amount")

    elif option == "1":
        if amount <= balance1:
            balance1 -= amount
            balance2 += amount
            print("Transfer successful")
        else:
            print("Insufficient balance in Account 1")

    elif option == "2":
        if amount <= balance2:
            balance2 -= amount
            balance1 += amount
            print("Transfer successful")
        else:
            print("Insufficient balance in Account 2")

    else:
        print("Invalid option")


while True:
    print("\n----- BANK MENU -----")
    print("1. Check Balance")
    print("2. Deposit Money")
    print("3. Withdraw Money")
    print("4. Transfer Money")
    print("5. Exit")

    choice = input("Enter your choice (1-5): ")

    if choice == "1":
        check_balance()

    elif choice == "2":
        deposit_money()

    elif choice == "3":
        withdraw_money()

    elif choice == "4":
        transfer_money()

    elif choice == "5":
        print("Thank you! Come again.")
        break

    else:
        print("Invalid choice! Try again.")

balance1 = 10000
balance2 = 5000
correct_pin = "1234"
user_name = ""

def login():
    global user_name
    attempts = 3
    user_name = input("Enter your name: ")

    while attempts > 0:
        pin = input("Enter your PIN: ")
        if pin == correct_pin:
            print("Login successful! Welcome", user_name)
            return True
        else:
            attempts -= 1
            print("Incorrect PIN. Attempts left:", attempts)

    print("Too many wrong attempts. Exiting...")
    return False

def check_balance():
    print("\nAccount 1 balance: Rs.", balance1)
    print("Account 2 balance: Rs.", balance2)


def deposit_money():
    global balance1, balance2

    acc = input("Deposit to (1 or 2): ")
    amount = float(input("Enter amount: "))

    if amount <= 0:
        print("Invalid amount")

    elif acc == "1":
        balance1 += amount
        print("Deposit successful")

    elif acc == "2":
        balance2 += amount
        print("Deposit successful")

    else:
        print("Invalid account")

def withdraw_money():
    global balance1, balance2

    acc = input("Withdraw from (1 or 2): ")
    amount = float(input("Enter amount: "))

    if amount <= 0:
        print("Invalid amount")

    elif acc == "1":
        if amount <= balance1:
            balance1 -= amount
            print("Withdrawal successful")
        else:
            print("Insufficient balance")

    elif acc == "2":
        if amount <= balance2:
            balance2 -= amount
            print("Withdrawal successful")
        else:
            print("Insufficient balance")

    else:
        print("Invalid account")

def transfer_money():
    global balance1, balance2

    print("1. Account 1 → Account 2")
    print("2. Account 2 → Account 1")

    option = input("Choose option (1 or 2): ")
    amount = float(input("Enter amount: "))

    if amount <= 0:

        print("Invalid amount")

    elif option == "1":
        if amount <= balance1:
            balance1 -= amount
            balance2 += amount
            print("Transfer successful")
        else:
            print("Insufficient balance in Account 1")

    elif option == "2":
        if amount <= balance2:
            balance2 -= amount
            balance1 += amount
            print("Transfer successful")
        else:
            print("Insufficient balance in Account 2")

    else:
        print("Invalid option")




if login():

    while True:
        print("\n----- BANK MENU -----")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Transfer Money")
        print("5. Exit")

        choice = input("Enter your choice (1-5): ")

        if choice == "1":
            check_balance()

        elif choice == "2":
            deposit_money()

        elif choice == "3":
            withdraw_money()

        elif choice == "4":
            transfer_money()

        elif choice == "5":
            print("Thank you! Come again.")
            break

        else:
            print("Invalid choice! Try again.")

balance1 = 10000
balance2 = 50000
password = "1234"
account_munber = "123456789"
transaction_history = []

def login():
    attempts = 3
    while attempts > 0:
        acc = input("Enter account number: ")
        pwd=input("enter password")
        if acc == account_munber and pwd == password:
            print("Login successful!")
            return True
        else:
            attempts -= 1
            print("invalid account number or password. Attempts left:", attempts)
    print("Too many wrong attempts. Exiting...")
    return False


def check_balance():
    print("\nAccount 1 balance: Rs.", balance1)
    print("Account 2 balance: Rs.", balance2)


def deposit_money():
    global balance1, balance2
    try:
        acc = input("Deposit to (1 or 2): ")
        amount = float(input("Enter amount: "))
        if amount <= 0:
            print("Invalid amount")
        elif acc == "1":
            balance1 += amount
            transaction_history.append(f"Deposited Rs.{amount} to Account 1")
            print("Deposit successful")
        elif acc == "2":
            balance2 += amount
            transaction_history.append(f"Deposited Rs.{amount} to Account 2")
            print("Deposit successful")
        else:
            print("Invalid account")
    except:
        print("Invalid input! Enter numbers only.")


def withdraw_money():
    global balance1, balance2
    try:
        acc = input("Withdraw from (1 or 2): ")
        amount = float(input("Enter amount: "))
        if amount <= 0:
            print("Invalid amount")
        elif acc == "1":
            if amount <= balance1:
                balance1 -= amount
                transaction_history.append(f"Withdrew Rs.{amount} from Account 1")
                print("Withdrawal successful")
            else:
                print("Insufficient balance")
        elif acc == "2":
            if amount <= balance2:
                balance2 -= amount
                transaction_history.append(f"Withdrew Rs.{amount} from Account 2")
                print("Withdrawal successful")
            else:
                print("Insufficient balance")
        else:
            print("Invalid account")
    except:
        print("Invalid input!")


def transfer_money():
    global balance1, balance2
    try:
        print("1. Account 1 → Account 2")
        print("2. Account 2 → Account 1")
        option = input("Choose option (1 or 2): ")
        amount = float(input("Enter amount: "))
        if amount <= 0:
            print("Invalid amount")
        elif option == "1":
            if amount <= balance1:
                balance1 -= amount
                balance2 += amount
                transaction_history.append(f"Transferred Rs.{amount} from A1 to A2")
                print("Transfer successful")
            else:
                print("Insufficient balance in Account 1")
        elif option == "2":
            if amount <= balance2:
                balance2 -= amount
                balance1 += amount
                transaction_history.append(f"Transferred Rs.{amount} from A2 to A1")
                print("Transfer successful")
            else:
                print("Insufficient balance in Account 2")
        else:
            print("Invalid option")
    except:
        print("Invalid input!")


def show_history():
    print("\n----- TRANSACTION HISTORY -----")

    if len(transaction_history) == 0:
        print("No transactions yet.")
    else:
        for t in transaction_history:
            print("-", t)



if login():

    while True:
        print("\n----- BANK MENU -----")
        print("1. Check Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Transfer Money")
        print("5. Transaction History")
        print("6. Exit")

        choice = input("Enter your choice (1-6): ")

        if choice == "1":
            check_balance()

        elif choice == "2":
            deposit_money()

        elif choice == "3":
            withdraw_money()

        elif choice == "4":
            transfer_money()

        elif choice == "5":
            show_history()

        elif choice == "6":
            print("Thank you!", user_name)
            break

        else:
            print("Invalid choice! Try again.")

cart = []
total = 0

def login():

    username = input("Enter username: ")
    password = input("Enter password: ")

    if username == "nishi" and password == "1234":
        print("\nLogin Successful!")
        main_menu()

    else:
        print("Wrong Username or Password")


def food_menu():

    global total
    while True:

      print("\n----- FOOD MENU -----")
      print("1. Burger - Rs.1200")
      print("2. Pizza - Rs.2500")
      print("3. Fries - Rs.800")
      print("4. Juice - Rs.500")
      print("5.Back")

      item = input("Select food item: ")

      if item == "1":
          cart.append("Burger")
          total += 1200
          print('"Burger" added to cart')

      elif item == "2":
          cart.append("Pizza")
          total += 2500
          print('"Pizza" added to cart')

      elif item == "3":
          cart.append("Fries")
          total += 800
          print('"Fries" added to cart')

      elif item == "4":
          cart.append("Juice")
          total += 500
          print('"Juice" added to cart')

      elif item=="5":
        break

      else:
          print("Invalid Item")


def view_cart():

    print("\n----- YOUR CART -----")

    if len(cart) == 0:
        print("Cart is empty")

    else:
        for food in cart:
            print(food)

        print("Current Total = Rs.", total)



def checkout():

    tax = total * 0.10
    delivery = 300
    final_amount = total + tax + delivery

    print("\n----- CHECKOUT -----")
    print("Food Total = Rs.", total)
    print("Tax = Rs.", tax)
    print("Delivery Charges = Rs.", delivery)
    print("Final Amount = Rs.", final_amount)


def main_menu():

    while True:

        print("\n----- MAIN MENU -----")
        print("1. View Food Menu")
        print("2. View Cart")
        print("3. Checkout")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            food_menu()

        elif choice == "2":
            view_cart()

        elif choice == "3":
            checkout()

        elif choice == "4":
            print("Thank You!")
            break

        else:
            print("Invalid Choice")

login()

cart = []
total = 0

def login():

    username = input("Enter username: ")
    password = input("Enter password: ")

    if username == "nishi" and password == "1234":
        print("\nLogin Successful!")
        main_menu()

    else:
        print("Wrong Username or Password")


def food_menu():

    global total

    while True:

        print("\n----- FOOD MENU -----")
        print("1. Burger - Rs.1200")
        print("2. Pizza - Rs.2500")
        print("3. Fries - Rs.800")
        print("4. Juice - Rs.500")
        print("5. Back")

        print("\nExample : 1,2,4")
        items = input("Select food items: ")

        if items == "5":
            break

        order_list = items.split(",")

        for item in order_list:

            if item == "1":

                qty = int(input("How many Burgers? : "))

                for i in range(qty):
                    cart.append(("Burger", 1200))

                total += 1200 * qty

                print(qty, "Burger added to cart")

            elif item == "2":

                qty = int(input("How many Pizzas? : "))

                for i in range(qty):
                    cart.append(("Pizza", 2500))

                total += 2500 * qty

                print(qty, "Pizza added to cart")


            elif item == "3":

                qty = int(input("How many Fries? : "))

                for i in range(qty):
                    cart.append(("Fries", 800))

                total += 800 * qty

                print(qty, "Fries added to cart")


            elif item == "4":

                qty = int(input("How many Juices? : "))

                for i in range(qty):
                    cart.append(("Juice", 500))

                total += 500 * qty

                print(qty, "Juice added to cart")

            else:
                print("Invalid Item")


def view_cart():

    print("\n----- YOUR CART -----")

    if len(cart) == 0:
        print("Cart is empty")

    else:

        count = len(cart)

        print("\nOrdered", count, "items\n")

        for food in cart:
            print(food[0], "- Rs.", food[1])

        print("\nCurrent Total = Rs.", total)



def checkout():

    tax = total * 0.10
    delivery = 300
    final_amount = total + tax + delivery

    print("\n----- CHECKOUT -----")
    print("Food Total = Rs.", total)
    print("Tax = Rs.", tax)
    print("Delivery Charges = Rs.", delivery)
    print("Final Amount = Rs.", final_amount)


def main_menu():

    while True:

        print("\n----- MAIN MENU -----")
        print("1. View Food Menu")
        print("2. View Cart")
        print("3. Checkout")
        print("4. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            food_menu()

        elif choice == "2":
            view_cart()

        elif choice == "3":
            checkout()

        elif choice == "4":
            print("Thank You!")
            break

        else:
            print("Invalid Choice")



login()

movies = {
    1: {"name": "Avengers", "price": 1200},
    2: {"name": "Avatar", "price": 1500},
    3: {"name": "Batman", "price": 1000},
    4: {"name": "Lion King", "price": 1500},
    5: {"name": "Minions", "price": 1200},
    6: {"name": "Aladdin", "price": 1000}
}
username = input("Enter Username: ")
password = input("Enter Password: ")

print("\nLogin Successful!")
print("Welcome", username)

grand_total = 0

while True:

    print("\nAvailable Movies")
    for key, value in movies.items():
        print(key, "-", value["name"], "- Rs.", value["price"])

    choice = int(input("\nSelect Movie Number: "))

    if choice in movies:

        movie_name = movies[choice]["name"]
        ticket_price = movies[choice]["price"]

        seats = int(input("Enter Number of Seats: "))

        amount = seats * ticket_price

        print("\nMovie:", movie_name)
        print("Ticket Price: Rs.", ticket_price)
        print("Seats:", seats)
        print("Amount: Rs.", amount)

        grand_total += amount

    else:
        print("Invalid Movie Selection!")

    more = input("\nDo you want to book more tickets? (yes/no): ")

    if more.lower() != "yes":
        break
print("\nTotal Amount = Rs.", grand_total)
print("Thank you for booking")

def login()
username = input("Enter username: ")
password = input("Enter password: ")

print("\nLogin Successful!")
print("Welcome", username)

total_amount = 0
book_more = "yes"
available_seats=50
movie_list = []
amount_list = []

while book_more.lower() == "yes":

    print("\nAvailable seats:",available_seats)
    print("\nAvailable Movies")
    print("1. Lion King - Rs.1200")
    print("2. Minions- Rs.1000")
    print("3. Spiderman - Rs.1500")
    print("4. Avatar-Rs.1800")

    choice = int(input("\nSelect movie number: "))


    if choice == 1:
        movie = "Lion King"
        price = 1200

    elif choice == 2:
        movie = "Minions"
        price=1000

    elif choice == 3:
        movie = "Spiderman"
        price = 1500

    elif choice==4:
       movie= "Avatar"
       price= 1800

    else:
        print("Invalid Choice")
        continue

    seats = int(input("Enter number of seats: "))

    if seats > available_seats:
        print("Sorry! Only", available_seats, "seats are available.")
        continue

    available_seats = available_seats - seats

    amount = seats * price

    print("\nMovie Name :", movie)
    print("Ticket Price :", price)
    print("Seats :", seats)
    print("Amount :", amount)

    movie_list.append(movie)
    amount_list.append(amount)

    total_amount = total_amount + amount

    book_more = input("\nDo you want to book more tickets? (yes/no): ")

print("\n--- BOOKING SUMMARY ---")

for i in range(len(movie_list)):
    print(movie_list[i], "- Rs.", amount_list[i])

print("\nTotal Amount = Rs.", total_amount)

print("Thank You for Booking!")
login()

# @title Default title text
movie_list = []
ticket_list = []
price_list = []
amount_list = []
theater_list = []

total_amount = 0

theater1_seats = 50
theater2_seats = 40
theater3_seats = 30

def login():

    username = input("Enter username: ")
    password = input("Enter password: ")

    print("\nLogin Successful!")
    print("Welcome", username)

def book_ticket():

    global total_amount
    global theater1_seats
    global theater2_seats
    global theater3_seats

    print("\nAvailable Movies")
    print("1. Avengers - Rs.1200")
    print("2. Batman - Rs.1000")
    print("3. Spiderman - Rs.1500")

    choice = int(input("\nSelect movie number: "))

    if choice == 1:
        movie = "Avengers"
        price = 1200
        theater = "theater 1"

        print("Available Seats in theater 1 =", theater1_seats)

    elif choice == 2:
        movie = "Batman"
        price = 1000
        theater = "theater 2"

        print("Available Seats in theater 2 =", theater2_seats)

    elif choice == 3:
        movie = "Spiderman"
        price = 1500
        theater = "theater 3"

        print("Available Seats in theater 3 =", theater3_seats)

    else:
        print("Invalid Choice")
        return

    seats = int(input("Enter number of tickets: "))

    if choice == 1:

        if seats > theater1_seats:
            print("Not enough seats available!")
            return

        theater1_seats = theater1_seats - seats

    elif choice == 2:

        if seats > theater2_seats:
            print("Not enough seats available!")
            return

        theater2_seats = theater2_seats - seats

    elif choice == 3:

        if seats > theater3_seats:
            print("Not enough seats available!")
            return

        theater3_seats = theater3_seats - seats


    amount = seats * price

    print("\nMovie Name :", movie)
    print("theater :", theater)
    print("Ticket Price :", price)
    print("Number of Tickets :", seats)
    print("Amount :", amount)

    movie_list.append(movie)
    ticket_list.append(seats)
    price_list.append(price)
    amount_list.append(amount)
    theater_list.append(theater)

    total_amount = total_amount + amount


def show_summary():

    print("\n------ BOOKING SUMMARY ------")

    for i in range(len(movie_list)):

        print("\nMovie :", movie_list[i])
        print("Hall :", theater_list[i])
        print("Ticket Price : Rs.", price_list[i])
        print("Number of Tickets :", ticket_list[i])
        print("Total : Rs.", amount_list[i])

    print("\nFinal Total Amount = Rs.", total_amount)

    print("\nThank You for Booking!")

login()

book_more = "yes"

while book_more.lower() == "yes":

    book_ticket()

    book_more = input("\nDo you want to book more tickets? (yes/no): ")

show_summary()

movie_list = []
amount_list = []
total_amount = 0
available_seats = 50

def login():

    username = input("Enter username: ")
    password = input("Enter password: ")

    print("\nLogin Successful!")
    print("Welcome", username)

def book_ticket():

    global total_amount
    global available_seats

    print("\nAvailable Seats :", available_seats)
    print("\nAvailable Movies")
    print("1. Lion King- Rs.1200")
    print("2. Minions - Rs.1000")
    print("3. Spiderman - Rs.1500")

    choice = int(input("\nSelect movie number: "))

    if choice == 1:
        movie = "Lion King"
        price = 1200

    elif choice == 2:
        movie = "Minions"
        price = 1000

    elif choice == 3:
        movie = "Spiderman"
        price = 1500

    else:
        print("Invalid Choice")
        return

    seats = int(input("Enter number of seats: "))
    if seats > available_seats:

        print("Sorry! Not enough seats available.")
        return

    available_seats = available_seats - seats

    amount = seats * price

    print("\nMovie Name :", movie)
    print("Ticket Price :", price)
    print("Seats :", seats)
    print("Amount :", amount)

    movie_list.append(movie)
    amount_list.append(amount)


    total_amount = total_amount + amount

def show_summary():

    print("\n--- BOOKING SUMMARY ---")

    for i in range(len(movie_list)):
        print(movie_list[i], "- Rs.", amount_list[i])

    print("\nTotal Amount = Rs.", total_amount)

    print("Thank You for Booking!")


login()

book_more = "yes"

while book_more.lower() == "yes":

    book_ticket()

    book_more = input("\nDo you want to book more tickets? (yes/no): ")

show_summary()

order=[]


def login():
  username=input("enter username:")
  password=input("enter password:")
  if username=="nishi" and password=="12345":
    print("loging successful")
    return True
  else:
    print("invalid password or usename ")
    return False


def add_order():
  order_id=input("enter order id")
  customer=input("enter customer name")
  item=[]
  while True:
    print("=====food manu======")
    print("1.pizza-Rs.2500")
    print("2.burger-Rs.1200")
    print("3.juice-550")
    print("4.back")

    choice=input("enter your item:")

    if choice=="4":
      if len(item)==0:
        print("choice at least one item")
        continue
      break

    try:
      qty=input("enter quantity:")
      if qty<=0:
        print("quantity must be gtrater than 0")
        continue
    except ValueError:
      print("invalid input")
      continue

    if choice=="1":
      food="pizza"
      amount=2500*qty

    elif choice=="2":
      food="burger"
      amount=1200*qty

    elif choice=="3":
      food="juice"
      amount=550*qty

    else:
      print("invalid choice")
      continue

    item.append({
        "food":food,
        "qty":qty,
        "amount":amount
    })

    print(f"{food} added successfully")

    order.append({
        "order_id":order_id,
        "customer_name":customer,
        "item":item,
        "status":"pending"
    })

    print("order saved successfully")


def view_order():
  if len(order)==0:
    print("no order found")
    return

  print("\n=====all order======")
  for order in order:
    print("order_id:",order["order_id"])
    print("customer name:",order["customer_name"])

    total=0
    for item in order["item"]:
      print("food:",item["food"])
      print("qty:",item["qty"])
      print("amount:",item["amount"])
      total+=item["amount"]

    print("total:",total)
    print("status:",order["status"])



def search_order():
  search=input("enter order id:")
  found=False

  for order in order:
    if order["order_id"]==search:
      print("=====order details======")
      print("order_id:",order["order_id"])
      print("customer name:",order["customer_name"])
      print("status:",order["status"])

      total=0
    for item in order["item"]:
      print("food:",item["food"])
      print("qty:",item["qty"])
      total+=item["amount"]

    print("total:",total)
    found=True
    break

  if not found:
    print("not order found")

def update_status():
  search=input("enter order id:")
  found=False

  for order in order:
    if order["order_id"]==search:
     print("current status",order["status"])
     print("1.pending")
     print("2.completed")

     status_choice=input("enter yoour choice(1 or 2):")

     if status_choice=="1":
       order["status"]="pending"
       print("status updated to pending")
     elif status_choice=="2":
       order["status"]="completed"
       print("status updated to completed")
     else:
       print("invalid choice")
       found=True
       break
  if not found:
    print("order not found")

def calculate_total_sale():
  sale=0
  for order in order:
    if order["status"]=="completed":
      for item in order["item"]:
        sale+=item["amount"]
    print("total sale is",sale)


def count_completed_order():
  count=0
  for order in order:
    if order["status"]=="completed" :
      count+=1
  print("total completed order",count)


def main_menu():
  while True:
    print("\n=====main menu======")
    print("1.add order")
    print("2.view order")
    print("3.search order")
    print("4.update status")
    print("5.calculate total sale")
    print("6.count completed order")
    print("7.exit")

    choice=input("enter your choice:")


    if choice=="1":
      add_order()

    if choice=="2":
      view_order()

    if choice=="3":
      search_order()

    if choice=="4":
      update_status()

    if choice=="5":
      calculate_total_sale()

    if choice=="6":
      count_completed_order()

if login():
  main_menu()